version: '3.9'

services:
  database:
    container_name: postgres
    image: postgres:15.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
  
  http:
    container_name: http
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 8080:8080